package:
  name: matplotlib
  version: 3.2.2

source:
  url: https://github.com/matplotlib/matplotlib/archive/v3.2.2.tar.gz
  sha256: dd4ff3e19f507a5a07612fa642e6e66fadbaf303483a43dc3acb04067f7ac522

  patches:
    - patches/fix_fonts.patch



  #   - patches/font_name_encoding.patch
  #   - patches/force_malloc_free.patch
  #   - patches/hardcoded_font_cache.patch
  #   - patches/reduce_cpp_exceptions.patch
  #   - patches/reduce-imports.patch
  #   - patches/disable_macosx_backend.patch

  extras:
    -
      - src/wasm_backend.py
      - lib/matplotlib/backends/wasm_backend.py
    -
      - src/setup.cfg
      - ./setup.cfg


build:
  cflags: -s USE_FREETYPE=1 -s USE_LIBPNG=1 -s USE_ZLIB=1
  ldflags: ../../../../emsdk/emsdk/.emscripten_cache/asmjs/libpng.bc
  post: |
    wget -O $SITEPACKAGES/matplotlib/mpl-data/fonts/ttf/Humor-Sans.ttf http://antiyawn.com/uploads/Humor-Sans-1.0.ttf
    rm -rf $SITEPACKAGES/matplotlib/backends/qt_editor
    rm -rf $SITEPACKAGES/matplotlib/backends/web_backend
    rm -rf $SITEPACKAGES/sphinxext
    cp $PKGDIR/src/fontlist-v201.json $SITEPACKAGES/matplotlib

requirements:
  run:
    - cycler
    - kiwisolver
    - numpy
    - pyparsing
    - python-dateutil
    - pytz

test:
  imports:
    - matplotlib
    - mpl_toolkits
