package:
  name: pandas
  version: 1.0.5

source:
  url: https://files.pythonhosted.org/packages/31/29/ede692aa6547dfc1f07a4d69e8411b35225218bcfbe9787e78b67a35d103/pandas-1.0.5.tar.gz
  sha256: 69c5d920a0b2a9838e677f78f4dde506b95ea8e4d30da25859db6469ded84fa8

  patches:
    # these patches can be found as commits in
    #    https://github.com/rth/scipy/tree/0.17.1-pyodide
    # on top of the v0.17.1 tag
    - patches/remove-lzma-warning.patch


build:
  cflags: -Wno-implicit-function-declaration

requirements:
  run:
    - numpy
    - python-dateutil
    - pytz

test:
  imports:
    - pandas
