package:
  name: xgboost
  version: 1.2.0
source:
  sha256: e5f4abcd5df6767293f31b7c58d67ea38b2689641a95b2cd8ca8935295097a36
  url: https://files.pythonhosted.org/packages/2a/8f/3b21e1a65ef54b1f536f5e31e6bae1eff72ab9e08655743a7a5435ce71fc/xgboost-1.2.0.tar.gz
  patches:
    - patches/xgboost.patch

requirements:
  run:
    - numpy
    - scipy

test:
  imports:
    - xgboost
